import type { NextPage } from "next";
import Head from "next/head";
import { Container, Flex, Text, Heading, Button } from "@chakra-ui/react";
import { useContext } from "react";
import { ConnectionContext } from "../context/ConnectionContext";

const Home: NextPage = () => {
	const { accounts, contract, connectWallet } = useContext(ConnectionContext);

	const wave = async () => {
		await contract?.wave();
	};

	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container
				color="white"
				flexDir="column"
				bgColor="black"
				height="100vh"
				alignItems="center"
			>
				<Flex h="30vh" alignItems="center">
					<Heading w="100%" fontSize="48px" textAlign="center">~HELLO~</Heading>
				</Flex>
				<Flex flexDir="column" textAlign="center">
					<Text fontSize="36px">
						My name is Jo Rocca and I am a blockchain dev!
					</Text>
					<Text fontSize="24px">Wave to me on chain:</Text>
					<Button
						bgColor="purple"
						color="white"
						w="300px"
						padding="10px"
						border="none"
						borderRadius="30px"
						alignSelf="center"
            fontSize="24px"
            onClick={accounts ? wave : connectWallet}
					>
						{accounts ? "Wave" : "Connect wallet"}
					</Button>
				</Flex>
			</Container>
		</Container>
	);
};

export default Home;
