import type { NextPage } from "next";
import Head from "next/head";
import { Container, Flex, Text, Heading, Button } from "@chakra-ui/react";
import { useContext, useEffect, useState } from "react";
import { ConnectionContext } from "../context/ConnectionContext";

const Home: NextPage = () => {
	const { accounts, contract, connectWallet } = useContext(ConnectionContext);
	const [totalWaves, setTotalWaves] = useState<number>();

	const wave = async () => {
		await contract?.wave();
	};

	const getWaves = async () => {
		console.log("Getting total waves");
		const waves = await contract?.getTotalWaves();
		if (waves) {
			console.log(Number(waves));
			const waveTotal = Number(waves);
			setTotalWaves(waveTotal);
		}
	};

	useEffect(() => {
		getWaves();
	}, [totalWaves]);

	return (
		<Flex>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Flex
				color="white"
				flexDir="column"
				bgColor="black"
				height="100vh"
				alignItems="center"
				w="100vw"
			>
				<Flex h="30vh" alignItems="center">
					<Heading w="100%" fontSize="48px" textAlign="center">
						~HELLO~
					</Heading>
				</Flex>
				<Flex flexDir="column" textAlign="center">
					<Text fontSize="36px">
						My name is Jo Rocca and I am a blockchain dev!
					</Text>
					<Button
						bgColor="purple"
						color="white"
						w="300px"
						padding="10px"
						border="none"
						borderRadius="30px"
						alignSelf="center"
						fontSize="24px"
						my="15px"
						onClick={accounts ? wave : connectWallet}
					>
						{accounts ? "Wave to me on chain!" : "Connect Metamask"}
					</Button>

					{accounts ? (
						<Flex justify="space-around" mt="50px" w="500px" alignSelf="center">
							<Text fontSize="24px">Total waves: {totalWaves}</Text>
							<Button
								bgColor="purple"
								color="white"
								w="300px"
								padding="10px"
								border="none"
								borderRadius="30px"
								alignSelf="center"
								fontSize="24px"
								onClick={getWaves}
							>
								Update wave total
							</Button>
						</Flex>
					) : null}
				</Flex>
			</Flex>
		</Flex>
	);
};

export default Home;
